language: java
jdk:
 - oraclejdk8
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "cb2e70630c53e23d767eb2923ac0f6c02fb3ebf5"
    token:
      secure: ""
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
script: ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
after_success:
 - bash <(curl -s https://codecov.io/bash)
